//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TWEngine.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static byte[] chat_able {
            get {
                object obj = ResourceManager.GetObject("chat_able", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] chat_mute {
            get {
                object obj = ResourceManager.GetObject("chat_mute", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] chat_ready {
            get {
                object obj = ResourceManager.GetObject("chat_ready", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] chat_talking {
            get {
                object obj = ResourceManager.GetObject("chat_talking", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end this session?.
        /// </summary>
        internal static string ConfirmEndSession {
            get {
                return ResourceManager.GetString("ConfirmEndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit this sample?.
        /// </summary>
        internal static string ConfirmExitSample {
            get {
                return ResourceManager.GetString("ConfirmExitSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start the game,
        ///even though not all players are ready?.
        /// </summary>
        internal static string ConfirmForceStartGame {
            get {
                return ResourceManager.GetString("ConfirmForceStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave this session?.
        /// </summary>
        internal static string ConfirmLeaveSession {
            get {
                return ResourceManager.GetString("ConfirmLeaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit this game?.
        /// </summary>
        internal static string ConfirmQuitGame {
            get {
                return ResourceManager.GetString("ConfirmQuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ContentAudio\x86.
        /// </summary>
        internal static string ContentAudio {
            get {
                return ResourceManager.GetString("ContentAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentMaps.
        /// </summary>
        internal static string ContentMaps {
            get {
                return ResourceManager.GetString("ContentMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ContentMisc\x86.
        /// </summary>
        internal static string ContentMisc {
            get {
                return ResourceManager.GetString("ContentMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ContentTextures\x86.
        /// </summary>
        internal static string ContentTextures {
            get {
                return ResourceManager.GetString("ContentTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Session.
        /// </summary>
        internal static string CreateSession {
            get {
                return ResourceManager.GetString("CreateSession", resourceCulture);
            }
        }
        
        internal static byte[] DeadWoods_MMP {
            get {
                object obj = ResourceManager.GetObject("DeadWoods_MMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Session.
        /// </summary>
        internal static string EndSession {
            get {
                return ResourceManager.GetString("EndSession", resourceCulture);
            }
        }
        
        internal static byte[] EnergyOff {
            get {
                object obj = ResourceManager.GetObject("EnergyOff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to the network session.
        /// </summary>
        internal static string ErrorDisconnected {
            get {
                return ResourceManager.GetString("ErrorDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must sign in a suitable gamer profile
        ///in order to access this functionality.
        /// </summary>
        internal static string ErrorGamerPrivilege {
            get {
                return ResourceManager.GetString("ErrorGamerPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host ended the session.
        /// </summary>
        internal static string ErrorHostEndedSession {
            get {
                return ResourceManager.GetString("ErrorHostEndedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while
        ///accessing the network.
        /// </summary>
        internal static string ErrorNetwork {
            get {
                return ResourceManager.GetString("ErrorNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host kicked you out of the session.
        /// </summary>
        internal static string ErrorRemovedByHost {
            get {
                return ResourceManager.GetString("ErrorRemovedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session is already full.
        /// </summary>
        internal static string ErrorSessionFull {
            get {
                return ResourceManager.GetString("ErrorSessionFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not found. It may have ended,
        ///or there may be no network connectivity
        ///between the local machine and session host.
        /// </summary>
        internal static string ErrorSessionNotFound {
            get {
                return ResourceManager.GetString("ErrorSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait for the host to return to
        ///the lobby before you can join this session.
        /// </summary>
        internal static string ErrorSessionNotJoinable {
            get {
                return ResourceManager.GetString("ErrorSessionNotJoinable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNA Live was not detected on your computer.  
        ///Therefore, the SystemLink &amp; Live Menu options are
        ///not availble. 
        ///.
        /// </summary>
        internal static string ErrorXNALiveNotAvailable {
            get {
                return ResourceManager.GetString("ErrorXNALiveNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Sessions.
        /// </summary>
        internal static string FindSessions {
            get {
                return ResourceManager.GetString("FindSessions", resourceCulture);
            }
        }
        
        internal static byte[] FlagMarker {
            get {
                object obj = ResourceManager.GetObject("FlagMarker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GreenValley_MMP {
            get {
                object obj = ResourceManager.GetObject("GreenValley_MMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (host).
        /// </summary>
        internal static string HostSuffix {
            get {
                return ResourceManager.GetString("HostSuffix", resourceCulture);
            }
        }
        
        internal static byte[] IFDTileBlueOff {
            get {
                object obj = ResourceManager.GetObject("IFDTileBlueOff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileBlueOn {
            get {
                object obj = ResourceManager.GetObject("IFDTileBlueOn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileBlueRdy {
            get {
                object obj = ResourceManager.GetObject("IFDTileBlueRdy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_Airplanes {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_Airplanes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_Buildings {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_Buildings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_People {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_People", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_Selected {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_Selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_Shields {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_Shields", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_Vehicles {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_Vehicles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGreyOff {
            get {
                object obj = ResourceManager.GetObject("IFDTileGreyOff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileMinimapWrap {
            get {
                object obj = ResourceManager.GetObject("IFDTileMinimapWrap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Session.
        /// </summary>
        internal static string JoinSession {
            get {
                return ResourceManager.GetString("JoinSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Session.
        /// </summary>
        internal static string LeaveSession {
            get {
                return ResourceManager.GetString("LeaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        internal static string Lobby {
            get {
                return ResourceManager.GetString("Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        internal static byte[] MenuBackgroundImage1a {
            get {
                object obj = ResourceManager.GetObject("MenuBackgroundImage1a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MenuBackgroundImage1b {
            get {
                object obj = ResourceManager.GetObject("MenuBackgroundImage1b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MenuBackgroundSpaceEclipse {
            get {
                object obj = ResourceManager.GetObject("MenuBackgroundSpaceEclipse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///A button, Space, Enter = ok
        ///B button, Esc = cancel.
        /// </summary>
        internal static string MessageBoxUsage {
            get {
                return ResourceManager.GetString("MessageBoxUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} joined.
        /// </summary>
        internal static string MessageGamerJoined {
            get {
                return ResourceManager.GetString("MessageGamerJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} left.
        /// </summary>
        internal static string MessageGamerLeft {
            get {
                return ResourceManager.GetString("MessageGamerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking....
        /// </summary>
        internal static string NetworkBusy {
            get {
                return ResourceManager.GetString("NetworkBusy", resourceCulture);
            }
        }
        
        internal static byte[] NetworkBusyIcon {
            get {
                object obj = ResourceManager.GetObject("NetworkBusyIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sessions found.
        /// </summary>
        internal static string NoSessionsFound {
            get {
                return ResourceManager.GetString("NoSessionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVE.
        /// </summary>
        internal static string PlayerMatch {
            get {
                return ResourceManager.GetString("PlayerMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        internal static string QuitGame {
            get {
                return ResourceManager.GetString("QuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        internal static string ResumeGame {
            get {
                return ResourceManager.GetString("ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Lobby.
        /// </summary>
        internal static string ReturnToLobby {
            get {
                return ResourceManager.GetString("ReturnToLobby", resourceCulture);
            }
        }
        
        internal static byte[] RoughLands_MMP {
            get {
                object obj = ResourceManager.GetObject("RoughLands_MMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RoundMeterClock {
            get {
                object obj = ResourceManager.GetObject("RoundMeterClock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RoundMeterClock_75 {
            get {
                object obj = ResourceManager.GetObject("RoundMeterClock_75", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_AAGun01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_AAGun01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_AAGun02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_AAGun02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_AAGun04_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_AAGun04_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_AAGun05_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_AAGun05_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Artilery01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Artilery01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld03_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld03_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld04_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld04_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld05_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld05_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld06_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld06_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld07_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld07_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld08_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld08_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld09_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld09_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld10_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld10_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld11_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld11_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB03_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB03_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB04_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB04_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB05_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB05_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB06_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB06_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB07_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB07_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB08_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB08_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB09_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB09_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB10_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB10_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB11_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB11_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB12_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB12_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB13_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB13_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB14_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB14_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB15_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB15_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bomber01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bomber01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bomber06_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bomber06_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bomber07_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bomber07_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Gunship02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Gunship02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Heli01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Heli01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Heli02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Heli02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Jeep01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Jeep01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Jeep03_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Jeep03_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank03_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank03_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank04_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank04_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank05_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank05_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank06_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank06_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank07_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank07_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank08_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank08_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank09_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank09_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank10_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank10_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank11_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank11_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Player.
        /// </summary>
        internal static string SinglePlayer {
            get {
                return ResourceManager.GetString("SinglePlayer", resourceCulture);
            }
        }
        
        internal static byte[] statusBarContainer {
            get {
                object obj = ResourceManager.GetObject("statusBarContainer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] statusBarGreen {
            get {
                object obj = ResourceManager.GetObject("statusBarGreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] statusBarOrange {
            get {
                object obj = ResourceManager.GetObject("statusBarOrange", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] statusBarRed {
            get {
                object obj = ResourceManager.GetObject("statusBarRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] statusBarYellow {
            get {
                object obj = ResourceManager.GetObject("statusBarYellow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Link.
        /// </summary>
        internal static string SystemLink {
            get {
                return ResourceManager.GetString("SystemLink", resourceCulture);
            }
        }
        
        internal static byte[] tmpFactorTileOn {
            get {
                object obj = ResourceManager.GetObject("tmpFactorTileOn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tmpWindMillTile {
            get {
                object obj = ResourceManager.GetObject("tmpWindMillTile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tmpWindMillTileOn {
            get {
                object obj = ResourceManager.GetObject("tmpWindMillTileOn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WinterWonderland_MMP {
            get {
                object obj = ResourceManager.GetObject("WinterWonderland_MMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
