//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource360 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource360() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TWEngine.Resource360", typeof(Resource360).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] chat_able {
            get {
                object obj = ResourceManager.GetObject("chat_able", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] chat_mute {
            get {
                object obj = ResourceManager.GetObject("chat_mute", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] chat_ready {
            get {
                object obj = ResourceManager.GetObject("chat_ready", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] chat_talking {
            get {
                object obj = ResourceManager.GetObject("chat_talking", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ContentAudio\Xbox360.
        /// </summary>
        internal static string ContentAudio {
            get {
                return ResourceManager.GetString("ContentAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ContentGroundTextures\Xbox360.
        /// </summary>
        internal static string ContentGroundTextures {
            get {
                return ResourceManager.GetString("ContentGroundTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentMaps.
        /// </summary>
        internal static string ContentMaps {
            get {
                return ResourceManager.GetString("ContentMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ContentMisc\Xbox360.
        /// </summary>
        internal static string ContentMisc {
            get {
                return ResourceManager.GetString("ContentMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ContentArtwork\Xbox360.
        /// </summary>
        internal static string ContentPlayable {
            get {
                return ResourceManager.GetString("ContentPlayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ContentArtwork\Xbox360.
        /// </summary>
        internal static string ContentScenary {
            get {
                return ResourceManager.GetString("ContentScenary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ContentTextures\Xbox360.
        /// </summary>
        internal static string ContentTextures {
            get {
                return ResourceManager.GetString("ContentTextures", resourceCulture);
            }
        }
        
        internal static byte[] EnergyOff {
            get {
                object obj = ResourceManager.GetObject("EnergyOff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FlagMarker {
            get {
                object obj = ResourceManager.GetObject("FlagMarker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileBlueOff {
            get {
                object obj = ResourceManager.GetObject("IFDTileBlueOff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileBlueOn {
            get {
                object obj = ResourceManager.GetObject("IFDTileBlueOn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileBlueRdy {
            get {
                object obj = ResourceManager.GetObject("IFDTileBlueRdy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_Airplanes {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_Airplanes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_Buildings {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_Buildings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_People {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_People", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_Selected {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_Selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_Shields {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_Shields", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGC_Vehicles {
            get {
                object obj = ResourceManager.GetObject("IFDTileGC_Vehicles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileGreyOff {
            get {
                object obj = ResourceManager.GetObject("IFDTileGreyOff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IFDTileMinimapWrap {
            get {
                object obj = ResourceManager.GetObject("IFDTileMinimapWrap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MenuBackgroundImage1a {
            get {
                object obj = ResourceManager.GetObject("MenuBackgroundImage1a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MenuBackgroundImage1b {
            get {
                object obj = ResourceManager.GetObject("MenuBackgroundImage1b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MenuBackgroundSpaceEclipse {
            get {
                object obj = ResourceManager.GetObject("MenuBackgroundSpaceEclipse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NetworkBusyIcon {
            get {
                object obj = ResourceManager.GetObject("NetworkBusyIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RoundMeterClock {
            get {
                object obj = ResourceManager.GetObject("RoundMeterClock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RoundMeterClock_75 {
            get {
                object obj = ResourceManager.GetObject("RoundMeterClock_75", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_AAGun01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_AAGun01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_AAGun02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_AAGun02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_AAGun04_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_AAGun04_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_AAGun05_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_AAGun05_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Artilery01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Artilery01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld03_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld03_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld04_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld04_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld05_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld05_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld06_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld06_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld07_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld07_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld08_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld08_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld09_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld09_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld10_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld10_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bld11_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bld11_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB03_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB03_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB04_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB04_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB05_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB05_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB06_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB06_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB07_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB07_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB08_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB08_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB09_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB09_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB10_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB10_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB11_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB11_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB12_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB12_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB13_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB13_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB14_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB14_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_BldB15_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_BldB15_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bomber01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bomber01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bomber06_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bomber06_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Bomber07_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Bomber07_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Gunship02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Gunship02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Heli01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Heli01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Heli02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Heli02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Jeep01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Jeep01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Jeep03_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Jeep03_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank01_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank01_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank02_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank02_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank03_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank03_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank04_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank04_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank05_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank05_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank06_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank06_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank07_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank07_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank08_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank08_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank09_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank09_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank10_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank10_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SciFi_Tank11_Pic {
            get {
                object obj = ResourceManager.GetObject("SciFi_Tank11_Pic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] statusBarContainer {
            get {
                object obj = ResourceManager.GetObject("statusBarContainer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] statusBarGreen {
            get {
                object obj = ResourceManager.GetObject("statusBarGreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] statusBarOrange {
            get {
                object obj = ResourceManager.GetObject("statusBarOrange", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] statusBarRed {
            get {
                object obj = ResourceManager.GetObject("statusBarRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] statusBarYellow {
            get {
                object obj = ResourceManager.GetObject("statusBarYellow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tmpFactorTileOn {
            get {
                object obj = ResourceManager.GetObject("tmpFactorTileOn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tmpWindMillTile {
            get {
                object obj = ResourceManager.GetObject("tmpWindMillTile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tmpWindMillTileOn {
            get {
                object obj = ResourceManager.GetObject("tmpWindMillTileOn", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
