#region File Description
//-----------------------------------------------------------------------------
// ItemType.cs
//
// Ben Scharbach - XNA Community Game Platform
// Copyright (C) Image-Nexus, LLC. All rights reserved.
//-----------------------------------------------------------------------------
#endregion

using ImageNexus.BenScharbach.TWEngine.ItemTypeAttributes;

namespace ImageNexus.BenScharbach.TWEngine.InstancedModels.Enums
{
    // Note: 10/11/2012 - This ENUM list MUST MATCH the list in the ScenaryDataLoader.
    ///<summary>
    /// <see cref="ItemType"/> Enum, which represents all usable artwork for the game engine.  Using
    /// the <see cref="ItemTypeAtts"/>, the given artwork name is then coupled with the proper artwork file, 
    /// and can be saved with any game map.  
    ///</summary>
    public enum ItemType
    {
#pragma warning disable 1591

        #region Winter-Set
// ReSharper disable InconsistentNaming
        winterTree01,
        winterTree02,
        winterTree03,
        winterTree04,
        winterTree05,
        winterTree06,
        winterTree07,
        winterTreeSnow01,
        winterTreeSnow02,
        winterTreeSnow03,
        winterTreeSnow04,
        winterTreeSnow05,
        winterTreeSnow06,
        winterTreeSnow07,
        winterBush01,
        winterBush02,
        winterDeadGrass01,
        winterDeadGrass02,
        winterDeadGrass03,
        winterLog01,
        winterLog02,
        winterLog03,
        winterStone01,
        winterStone02,
        winterStone03,
        winterStone04,
        winterStone05,
        winterStoneSnow01,
        winterStoneSnow02,
        winterStoneSnow03,
        winterStoneSnow04,
        winterStoneSnow05,
        winterStoneArch01,
        winterStoneArch02,
        winterStoneArch03,
        winterStoneArch04,
        winterStoneArch05,
        winterRock01,
        winterRock02,
        winterRock03,
        winterRock04,
        winterRock05,
        winterRock06,
        winterRockSnow01,
        winterRockSnow02,
        winterRockSnow03,
        winterRockSnow04,
        winterRockSnow05,

        #endregion

        #region Desert-Set

        desertTree01,
        desertTree02,
        desertTree03,
        desertTree04,
        desertTreeSmall01,
        desertTreeSmall02,
        desertTreeSmall03,
        desertTreeSmall04,
        desertFlower,
        yuccaPlant,
        yukaPlant,
        desertGrass01,
        desertGrass02,
        desertBush01,
        desertRock01,
        desertRock02,
        desertRock03,
        desertRock04,
        desertRock05,
        desertRock06,

        #endregion

        #region Farm-Set

        farmBarn01,
        farmBarn02,
        farmBarn03,
        farmChurch01,
        farmOutBuilding01,
        farmOutBuilding02,
        farmSmallBarn01,
        farmSmallBarn02,
        farmWindMill,
        farmWaterMill,
        farmOakTree01,
        farmOakBush01,
        farmBrush01,
        farmBrush02,
        farmFlower01,
        farmFlower02,
        farmPumpkin01,
        farmPumpkin02,
        farmPumpkin03,
        farmPumpkinVine01,
        farmPumpkinVine02,
        farmPumpkinVine03,
        farmWeed01,
        farmBridge01,
        farmBarrel01,
        farmBarrel02,
        farmBarrelSet01,
        farmBarrelSet02,
        farmBarrelSet03,
        farmBarrelSet04,
        farmBarrelSet05,
        farmBarrelSet06,
        farmBarrelSet07,
        farmSmallCrate01,
        farmSmallCrate02,
        farmSmallCrateOpen01,
        farmSmallCrateOpen02,
        farmSmallCrateSet01,
        farmSmallCrateSet02,
        farmWoodenCrate01,
        farmWoodenCrateOpen01,
        farmWoodenCrateOpen02,
        farmWoodenCrateSet01,
        farmWoodenCrateSet02,
        farmWoodenCrateSet03,
        farmWoodenCrateSet04,
        farmWoodenCrateSet05,
        farmWestBarn01,
        farmWestBarn02,
        farmWestBarn03,
        farmWestBarn04,
        farmWestBarn05,
        farmWestBarn06,
        farmWestBarn07,
        farmWestChurch01,
        farmWestOutBuilding01,
        farmWestOutBuilding02,
        farmWestSilo01,
        farmWestSilo02,
        farmWestSilo03,
        farmWestSilo04,
        farmWestSilo05,
        farmWestSmallBarn01,
        farmWestSmallBarn02,
        farmWestSmallBarn03,
        farmWestWaterTower01,
        farmWestWaterTower02,
        farmLampPost01,
        farmLampPost02,
        farmLampPost03,
        farmLampPost04,
        farmLampPost05,
        farmLampPost06,
        farmHeadStone01,
        farmHeadStone02,
        farmHeadStone03,
        farmHeadStone04,
        farmHeadStone05,
        farmHeadStone06,
        farmHeadStone07,
        farmHeadStone08,
        farmHeadStone09,
        farmTombStone01,
        farmTombStone02,
        farmTombStone03,
        farmTombStone04,
        farmTombStone05,
        farmTombStone06,
        farmTombStone07,
        farmTombStone08,
        farmTombStone09,

        #endregion

        #region Volcanic-Set

        volcanicTree01,
        volcanicTree02,
        volcanicTree03,
        volcanicTree04,
        volcanicTree05,
        volcanicBush01,
        volcanicBush02,
        volcanicBush03,

        #endregion

        barbWireCorner,
        barbWireStraight01,
        stoneWallCorner01,
        stoneWallStraight01,


        #region Swamp-Set

        swampTree01,
        swampTree02,
        swampTree03,
        swampStump01,
        swampStump02,
        swampStump03,
        swampStump04,
        swampFern01,
        swampFern02,
        swampGrass01,
        swampGrass02,
        swampGrassCatTail01,
        swampGrassCatTail02,
        swampPalm01,
        swampPalm02,
        swampTemple01,
        swampTemple02,
        swampTemple03,
        swampTemple04,
        swampTemple05,
        swampPillar01,
        swampPillar02,
        swampPillar03,
        swampPlatform01,
        swampPlatform02,
        swampPlatform03,

        #endregion

        #region UrbanPack-Set

        urbanCargoContainer,
        urbanWoodenCrate,
        urbanTrafficCone,
        urbanChainLinkFence,
        urbanBarricade,
        urbanPlasticBarrel,
        urbanCardboardBox,
        urbanCardboardBox2,
        urbanWoodPallet,
        urbanWoodPallet2,
        urbanDumpster,
        urbanSpareTire,

        #endregion

        #region Sticks N Twiggs-Set

        treeAspen001,
        treeAspen002,
        treeGreen001,
        treeGreen002,
        treeGreen003,
        treeGreen004,
        treeGreen005,
        treeGreen007,
        treeOak002,
        treeOak004,
        treeOak005,
        treeOak006,
        treeOak007,
        treeOak008,
        treeOldOak001,
        treeOldOak002,
        treeOldOak003,
        treeOldOak004,
        treeOldOak005,
        treePalm002,
        treePalm003,
        treePalm004,
        treePalm005,
        treePalmNew001,
        treePalmNew002a,
        treePalmNew002b,
        treePalmNew002c,
        treePalmNew003,
        treePine001,
        treePine002,
        treePine003,
        treePine004,
        treePine005,
        treeWhite001,
        treeWhite002,
        treeWhite003,
        treeWhite004,
        treeWhite005,
        plantsCactus001,
        plantsNewWeeds001,
        plantsNewWeeds002,
        plantsNewWeeds003,
        plantsNewWeeds004,
        plantsNewWeeds005,
        plantsNewWeeds006,
        plantsNewBushes001,
        plantsNewBushes002,
        plantsNewBushes003,
        plantsNewBushes004,
        plantsBushesBrwn001,
        plantsBushesBrwn002,
        plantsBushesBrwn003,
        plantsBushesGrn001,
        plantsBushesGrn002,
        plantsFern1_001,
        plantsFern1_002,
        plantsFern1_003,
        plantsFern2_001,
        plantsFern2_002,
        plantsFern2_003,
        plantsFern3_001,
        plantsFern3_002,
        plantsFern3_003,
        plantsGrass001,
        plantsTwig001,
        plantsTwig002,
        treeJungle003,
        treeJungle004,
        treeJungle005,
        treeJungle006,
        treeJungle007,
        treeJungle008,
        treeGrnArch001,
        treeGrnArch002,
        treeGrnArch003,
        treeGrnArch004,
        treeGrnArch007,
        treeGrnArch008,
        treeGrnArch009,
        treeDeadSplt001,
        treeDeadSplt002,
        treeGrnSplt001,
        treeGrnSplt002,
        treeGrnSplt003,
        treePalm006,
        asstRocks001,
        asstRocks001a,
        asstRocks002,
        asstRocks002a,
        asstRocks003,
        asstRocks003a,
        asstRocks004a,
        asstRocks005a,
        asstRocks006a,
        asstRocksFlatBottom001,
        asstRocksRound001,
        asstRocksRound002,
        asstRocksRound003,
        asstRocksRound004,

        #endregion

        #region AlleyPack-Set

        barrel003,
        barrel004,
        barrel005,
        barrel006,
        barrel009,
        cardboardBOX,
        cardboardBoxSmallFragile,
        cardboardBOXdamaged,
        cinderBlockPile,
        cinderBlockQuad,
        cinderBlockSingle,
        cinderBlockWall,
        crateFragile0051,
        crateFragileDMGED,
        cratePlain009,
        cratePlainDMGED,
        cratePlainDMGED034,
        cratePlainDMGED035,
        cratePlainDMGED2,
        cratePlainPOTATOES,
        cratePlainSLATS,
        fireEscape01,
        fireEscape01down,
        fireEscape01upper,
        fireHydrantRed,
        fireHydrantYellow01,
        mailBoxBlue001,
        plywoodSheet1,
        plywoodSheet2leaning,
        plywoodSheet3,
        busStopBench001,
        busStopBenchAd001,
        sign_20MPH,
        sign_25MPH,
        sign_DEADEND,
        sign_DONOTENTER,
        sign_INTERSECT,
        sign_LEFT,
        sign_NOOUTLET,
        sign_NOPARKING,
        sign_NOPARKING2,
        sign_NOPARKING3,
        sign_NOPARKING4,
        sign_NOUTURN,
        sign_PEDX,
        sign_RIGHT,
        sign_RR,
        sign_STOP,
        tireSIDE,
        tireSIDEx3,
        trashCan,
        TVantenna001,
        TVantenna002,
        TVantenna003,
        TVantenna003a,
        wood2x4,
        wood2x4strewn,
        woodPalette1,
        woodPalette2,
        woodPalette3,
        woodPalette4_broken,
        woodPlankSingle,
        woodPlankTriple_leaning,
        woodPlankTriple2_leaning,
        woodPlankTriple2b_leaning,

        #endregion

        #region DowntownDistrict-Set

        cgBuilding0035,
        cgBuilding0050,
        cgRedBrick40sGarage,
        cgTrashBinRusted001,
        cgTrashBinRusted002wTrash,
        cgTrashBinRusted003wTrashFull,
        cityBlock001,
        plazaHotel001AthreeStory,
        plazaHotel002A,
        plazaHotelSign001,
        sidewalkSectionL,
        sidewalkSectionLshort,
        signAdultCinema001,
        stopSignal001,
        streetSidewalk001,
        streetSidewalk001damaged,
        streetBrokenMiddle001damaged1,
        streetCrosswalk001,
        streetCrosswalk001damaged,
        streetCuldesac001,
        streetCuldesac001damaged,
        streetEndBroken001damaged,
        streetIntersection4W,
        streetIntersection4Wdamaged,
        streetLight001,
        streetLongSec001,
        streetLongSecSidewalk001,
        streetLongSecSidewalk001damaged,
        streetThreeWayInt001,
        streetThreeWayInt001damaged,
        tmApartmentSmall001,
        tmApartmentSmall2x001,
        tmBuilding001,
        tmBuilding001storeFront001,
        tmBuilding002A,
        tmBuilding003Atwin2cooling,
        tmMuseum001,

        #endregion

        #region WarehouseDistrict-Set

        alleyWallBrick001,
        alleyWallBrick002,
        alleyWallConcrete001,
        alleyWallConcrete002,
        alleyWallConcrete003graf,
        autoGarage001,
        cargoContainerT001,
        cargoContainerT002,
        cargoContainerT003,
        cargoContainerT004,
        cargoContainerT005,
        cargoContainerT006,
        cargoContainerTopen001,
        cargoContainerTopen002Blue,
        cargoContainerTopen002dirty1,
        cargoContainerTopen002Org,
        cgBuildingRuin002,
        cgBuildingRuin002twin,
        cgWarehouse002story,
        cgWarehouse001enclosed,
        concreteBarricade001,
        concreteBarricade003,
        concreteBarricade004,
        concreteBarricadeV2_001warning,
        concreteBarricadeWwarning001,
        grafittiBarricade001,
        grafittiBarricade002,
        cgConcreteWarehouse001,
        garageSign001,
        signTattoo001,
        oldWarehouse001,
        oldWarehouse001worn,
        oldWarehouse001worn2,
        oldWarehouse004,
        rustedWarehouse001,
        tinBuilding001,
        tinBuilding002,
        tractorTrailer001,
        tractorTrailer001blue,
        tractorTrailer001dirty01,
        tractorTrailer001dirty03,

        #endregion

        #region Playable Units and Buildings

        sciFiBlda01,
        sciFiBlda02,
        sciFiBlda03,
        sciFiBlda04,
        sciFiBlda05,
        sciFiBlda06,
        sciFiBlda07,
        sciFiBlda08,
        sciFiBlda09,
        sciFiBlda10,
        sciFiBlda11,
        sciFiBldb01,
        sciFiBldb02,
        sciFiBldb03,
        sciFiBldb04,
        sciFiBldb05,
        sciFiBldb06,
        sciFiBldb07,
        sciFiBldb08,
        sciFiBldb09,
        sciFiBldb10,
        sciFiBldb11,
        sciFiBldb12,
        sciFiBldb13,
        sciFiBldb14,
        sciFiBldb15,
        sciFiTank01,
        sciFiTank02,
        sciFiTank03,
        sciFiTank04,
        sciFiTank05,
        sciFiTank06,
        sciFiTank07,
        sciFiTank08,
        sciFiTank09,
        sciFiTank10,
        sciFiTank11,
        sciFiAAGun01,
        sciFiAAGun02,
        sciFiHeli01,
        sciFiHeli02,
        sciFiGunShip01,
        sciFiGunShip02,
        sciFiAAGun04,
        sciFiAAGun05,
        sciFiBomber01,
        sciFiBomber06,
        sciFiBomber07,
        sciFiArtilery01,
        sciFiJeep01,
        sciFiJeep03,
        flagMarker,

        #endregion

        testItem,
        farmWestWindMill,
        farmWestWaterMill,
#pragma warning restore 1591

    }
}